accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView, \
    UserVerificationView

app_name = 'accountapp'



urlpatterns = [


    path('login/',LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('verify/<pk>/<token>/', UserVerificationView.as_view(), name='verify'),
    path('create/',AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>',AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>',AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>',AccountDeleteView.as_view(), name='delete'),
]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    ArticleListView, private_view

app_name = 'articleapp'

urlpatterns = [

    path('list/',ArticleListView.as_view(),name='list'),
    path('private/',private_view,name='private'),
    path('create/',ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>',ArticleDetailView.as_view(),name='detail'),
    path('update/<int:pk>',ArticleUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',ArticleDeleteView.as_view(),name='delete'),
]

butter/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView

urlpatterns = [
    path('',ArticleListView.as_view(),name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('articles/', include('articleapp.urls')),
    path('comments/', include('commentapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('subscribe/', include('subscribeapp.urls')),
    path('likes/', include('likeapp.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectListView, ProjectCreateView, ProjectDetailView

app_name='projectapp'

urlpatterns=[
    path('list/',ProjectListView.as_view(),name='list'),
    path('create/',ProjectCreateView.as_view(),name='create'),
    path('detail/<int:pk>',ProjectDetailView.as_view(),name='detail'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView, SubscriptionFollowView

app_name='subscribeapp'

urlpatterns=[
    path('subscribe/',SubscriptionView.as_view(),name='subscribe'),
    path('list/',SubscriptionListView.as_view(),name='list'),
    path('follow/',SubscriptionFollowView.as_view(),name='follow'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<header>
    {%include 'header.html'%}
</header>
<body style="font-family:'NanumSquareRoundOTFR'; background-color:#D5F1FF; " >

    <div class="left">
        {% include 'side_left.html' %}
    </div>

    <div class="center">
        {% for message in messages %}

    <div class = 'text-center' >
        <div class="btn btn-{{ message.tags }} rounded-pill px-5 my-3">
            {{ message }}
        </div>
    </div>
    {% endfor %}
    {% block content %}
    {% endblock %}
    </div>

<!--    <div class="right">
        개발중입니다.
    </div>-->

    <div class="footer">
        {%include 'footer.html'%}
    </div>



</body>
</html>

templates/footer.html
<div class="butter_footer">
    <div class="butter_footer_button">
        <span>공지사항</span> |
        <span><a href="{% url 'articleapp:private' %}">개인정보처리방침</a></span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top: 1rem;">
        <h6 class="butter_logo" >Shookiki</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Shookiki</title>

    <!--  BOOTSTRAP LINK  -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <!--  GOOGLE FONTS LINK  -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Hanalei+Fill&display=swap" rel="stylesheet">
    <!-- GOOGLE MATERIAL ICONS -->
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
    <!--  DEFAULT CSS LINK  -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'reset.css' %}">

    <style>
        @font-face {
            font-family: 'NanumSquareRoundOTFB';
            src: local('NanumSquareRoundOTFB'),
            url("{% static 'fonts/NanumSquareRoundOTFB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareRoundOTFEB';
            src: local('NanumSquareRoundOTFEB'),
            url("{% static 'fonts/NanumSquareRoundOTFEB.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareRoundOTFL';
            src: local('NanumSquareRoundOTFL'),
            url("{% static 'fonts/NanumSquareRoundOTFL.otf' %}") format("opentype");
        }
        @font-face {
            font-family: 'NanumSquareRoundOTFR';
            src: local('NanumSquareRoundOTFR'),
            url("{% static 'fonts/NanumSquareRoundOTFR.otf' %}") format("opentype");
        }
    </style>
</head>

templates/header.html
<div class="butter_header pop container-fluid fixed-top mb-1">
        <div>
            <a href="{% url 'home' %}"><h1 class="butter_logo" style="font-size:3rem;">Shookiki</h1></a>
        </div>
        <div class="header_nav" style="text-align:right; margin-right:2rem;">
            <!--<a href="{% url 'articleapp:list' %}" class="header_nav">
                <span>Articles</span>
            </a>
            <a href="{% url 'projectapp:list' %}" class="header_nav">
            <span>Projects</span>
            </a>
            <a href="{% url 'subscribeapp:list' %}" class="header_nav">
            <span>Subscription</span>
            </a>-->
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login'%}?next={{request.path}}" class="header_nav">
                <span>Login</span>
            </a>
            <a href="{% url 'accountapp:create' %}" class="header_nav">
                <span>SignUp</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}" class="header_nav">
                <span>MyPage</span>
            </a>
            <a href="{% url 'accountapp:logout'%}?next={{request.path}}" class="header_nav">
                <span>Logout</span>
            </a>
            {% endif %}
        </div>
</div>

templates/side_left.html
<div class="left_top">
    <a href="#menu" id="toggle">
        <i class="material-icons">favorite</i>
    </a>

    <div id="menu">
      <ul>
        <li><a href="{% url 'articleapp:list'%}">Articles</a></li>
        <li><a href="{% url 'projectapp:list' %}">Projects</a></li>
        <li><a href="{% url 'subscribeapp:list' %}">Subscription</a></li>
      </ul>
    </div>
</div>


    <!--<div id="category" style="visibility:hidden;">
        <span>a</span>
        <span>b</span>
        <span>c</span>
    </div>-->

<!--
{% if  user.is_authenticated %}
    <div class="shookikies">
        <h2>Shookikies</h2>
        <ul class="profile-list">
            <li class="profile-list&#45;&#45;item">
            <header class="profile-details">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/5175/cadet-mahoney.jpg" alt="" class="profile-img" />
            <h3 class="profile-name">Carey Mahoney</h3>
            </header>
            </li>
            <li class="profile-list&#45;&#45;item">
            <header class="profile-details">
            <img src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/5175/cadet-mahoney.jpg" alt="" class="profile-img" />
            <h3 class="profile-name">Carey</h3>
            </header>
            </li>
        </ul>
    </div>
{% endif %}-->













<script>
function on_display(){
    if(document.getElementById('category').style.visibility == "visible"){
        document.getElementById('category').style.visibility="hidden";
    }
    else{
        document.getElementById('category').style.visibility="visible";
    }
}
</script>


<script>
    var theToggle = document.getElementById('toggle');

// based on Todd Motto functions
// https://toddmotto.com/labs/reusable-js/

// hasClass
function hasClass(elem, className) {
	return new RegExp(' ' + className + ' ').test(' ' + elem.className + ' ');
}
// addClass
function addClass(elem, className) {
    if (!hasClass(elem, className)) {
    	elem.className += ' ' + className;
    }
}
// removeClass
function removeClass(elem, className) {
	var newClass = ' ' + elem.className.replace( /[\t\r\n]/g, ' ') + ' ';
	if (hasClass(elem, className)) {
        while (newClass.indexOf(' ' + className + ' ') >= 0 ) {
            newClass = newClass.replace(' ' + className + ' ', ' ');
        }
        elem.className = newClass.replace(/^\s+|\s+$/g, '');
    }
}
// toggleClass
function toggleClass(elem, className) {
	var newClass = ' ' + elem.className.replace( /[\t\r\n]/g, " " ) + ' ';
    if (hasClass(elem, className)) {
        while (newClass.indexOf(" " + className + " ") >= 0 ) {
            newClass = newClass.replace( " " + className + " " , " " );
        }
        elem.className = newClass.replace(/^\s+|\s+$/g, '');
    } else {
        elem.className += ' ' + className;
    }
}

theToggle.onclick = function() {
   toggleClass(this, 'on');
   return false;
}
</script>

templates/side_right.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>